Added debug message

diff --git a/.github/workflows/terraform_fmt.yml b/.github/workflows/terraform_fmt.yml
--- a/.github/workflows/terraform_fmt.yml
+++ b/.github/workflows/terraform_fmt.yml
@@ -26,4 +26,4 @@ jobs:
     
       - name: check
         if: steps.fmt.outcome != ''
-        run: exit 1
+        run: echo 'Formatting and styling failed!' && exit 1
